const projects = [
  {
    title: "Real Estate Analytics Dashboard",
    body: "This is a personal project that I created using NodeJS and React server-side rendering (Next.JS). Real Estate Analytics Dashboard was built to visualize and analyze the average real estate prices of different locations in Vietnam in different formats including geo-map, pie chart and table. The application uses data crawled from a Vietnamese real estate website, stored in MongoDB and used Apollo Server for GraphQL API service.",
    imageLinks: [
      "/images/raa-home.PNG",
      "/images/raa-cities.PNG",
      "/images/raa-count.PNG",
      "/images/raa-price.PNG",
      "/images/raa-charts.PNG",
    ],
    github: "https://github.com/ductuannguyen134/real-estate-analytics",
    technologies: [
      "Cheerio",
      "NodeJS",
      "GraphQL",
      "Apollo",
      "GitHub",
      "React",
      "Next.JS",
      "MongoDB",
      "TailwindCSS",
    ],
  },
  {
    title: "I Owe U (Advanced Internet Programming - SP2020)",
    body: "Me and my teammates created a web application that allows users to log in, record and resolve public requests, favors and debts using MERN stack. My responsibility was building the frontend using ReactJS, and support the other team members with the backend using NodeJS.",
    imageLinks: ["/images/iou.png"],
    github: "https://github.com/ductuannguyen134/aip2020-a2",
    technologies: [
      "NodeJS",
      "React (CRA)",
      "REST Api",
      "GitHub",
      "MongoDB",
      "ExpressJS",
    ],
  },
  {
    title: "Whatsapp Clone",
    body: "I have created a web application that works similar to Whatsapp web app, which includes real-time one-to-one chatting using Pusher, group chats and a contact list. The server was powered by ExpressJS and the database is stored in MongoDB. The frontend was built by React.",
    imageLinks: ["/images/whatsapp-clone.jpg"],
    github: "https://github.com/ductuannguyen134/whatsapp-clone-mern",
    technologies: [
      "NodeJS",
      "React (CRA)",
      "REST Api",
      "GitHub",
      "MongoDB",
      "ExpressJS",
      "Pusher",
    ],
  },
  {
    title: "This Portfolio !",
    body: "This porfolio was built using Next.JS and Sass. All components and styles are written from scratch.",
    imageLinks: ["/images/portfolio.PNG"],
    github: "https://github.com/ductuannguyen134/portfolio-v3",
    technologies: ["React", "Next.JS", "Sass"],
  },
  {
    title: "Weather Mobile Application",
    body: "This mobile app visualizes the weather data in all cities in the world using a public weather API. The app is cross-platform, and is powered by React Native Expo.",
    imageLinks: [
      "/images/weather-1.jpg",
      "/images/weather-2.jpg",
      "/images/weather-3.jpg",
      "/images/weather-4.jpg",
    ],
    github: "https://github.com/ductuannguyen134/weatherAppRN",
    technologies: ["Expo", "React Native"],
  },
];

export default projects;
